export const PERMISSIONS = {
  dashboard: "View Dashboard",
  view_accounts: "View Accounts",
  view_expense: "View Expense",
  view_digital_payment: "View Digital Payments",
  add_digital_payment: "Create Digital Payments",
  tally_digital_payment: "Tally Digital Payments",
  view_employees: "View Employees",
  add_employees: "Add Employees",
  view_salary_advance: "View Salary Advance",
  add_salary_advance: "Add Salary Advance",
  view_department: "View Departments",
  add_department: "Add Departments",
  view_family: "View Family",
  add_family: "Add Family",
  view_product_department: "View Product Department",
  view_resignation: "View Resignation",
  add_resignation: "View Resignation",
  view_without_adhaar: "View Without Adhaar",
  view_products: "View Products",
  view_category: "View Category",
  view_subcategory: "View Sub Category",
  view_designation: "View Designation",
  add_designation: "Add Designation",
  view_shift: "View Shifts",
  add_shifts: "Add Shifts",
  view_store_budget: "View Store Budget",
  view_whatsapp_order: "View Whatsapp Order",
  view_vehicle: "View Vehicle",
  add_store_budger: "Add Store Budget",
  view_customers: "View Customers",
  add_customers: "Add Customers",
  view_whatsapp_order: "View WhatsApp Orders",
  add_whatsapp_order: "Add WhatsApp Orders",
  view_suppliers: "View Suppliers",
  add_suppliers: "Add Suppliers",
  view_brands: "View Brands",
  // add_brands: "Add Brands",
  view_materials_request: "View Materials Request",
  add_materials_request: "Add Materials Request",
  view_materials_master: "View Materials Master",
  add_materials_master: "Add Materials Master",
  view_open_issues: "View Open Issues",
  add_open_issues: "Add Open Issues",
  view_all_issues: "View All Issues",
  add_issue: "Add Issue",
  view_service_provider: "View Service Provider",
  add_service_provider: "Add Service Provider",
  view_stores: "View Stores",
  view_banks: "View Banks",
  add_banks: "Add Banks",
  view_documents: "View Documents",
  view_reminders: "View Reminders",
  add_reminders: "Add Reminders",
  view_checklists: "View Checklists",
  add_checklists: "Add Checklists",
  view_checklist_report: "View Daily Checklist Report",
  view_grn: "View GRN",
  update_grn: "Update GRN",
  view_items: "View Items",
  add_repack_items: "Add Repack Items",
  new_items_request: "Add Item Requests",
  batch_verification: "Batch Verification",
  cleaning_packing: "View Cleaning and Packing",
  upload_cleaning_packing: "Upload Cleaning and Packing Requirements",
  add_grinding: "Add Grinding List",
  offers: "View Offers",
  add_item_offer: "Add Item Offers",
  add_brand_offer: "Add Brand Offers",
  view_damages: "View Damages",
  add_damages: "Add Damages",
  view_indents: "View Indents",
  received_indents: "Received Indents",
  sent_indents: "Sent Indents",
  accept_indents: "Accept Indents",
  add_dispatch: "Add Dispatch",
  accept_dispatch: "Accept Dispatch",
  view_issues_received_indents: "View Issues in Received Indents",
  view_issues_sent_indents: "View Sent in Received Indents",
  add_account_sheet: "Add Account Sheet",
};
