export const icons = {
  // Core
  menu: '<i class="fa-solid fa-bars"></i>',
  filter: '<i class="fa-solid fa-filter"></i>',
  columns: '<i class="fa-solid fa-table-columns"></i>',
  sortAscending: '<i class="fa-solid fa-arrow-up"></i>',
  sortDescending: '<i class="fa-solid fa-arrow-down"></i>',
  sortUnSort: '<i class="fa-solid fa-sort"></i>',
  first: '<i class="fa-solid fa-angles-left"></i>',
  previous: '<i class="fa-solid fa-angle-left"></i>',
  next: '<i class="fa-solid fa-angle-right"></i>',
  last: '<i class="fa-solid fa-angles-right"></i>',
  smallDown: '<i class="fa-solid fa-caret-down"></i>',
  smallUp: '<i class="fa-solid fa-caret-up"></i>',
  smallLeft: '<i class="fa-solid fa-caret-left"></i>',
  smallRight: '<i class="fa-solid fa-caret-right"></i>',
  smallCross: '<i class="fa-solid fa-xmark"></i>',

  checkboxChecked: '<i class="fa-solid fa-square-check"></i>',
  checkboxUnchecked: '<i class="fa-regular fa-square"></i>',
  checkboxIndeterminate: '<i class="fa-solid fa-square-minus"></i>',
  radioButtonOn: '<i class="fa-solid fa-dot-circle"></i>',
  radioButtonOff: '<i class="fa-regular fa-circle"></i>',

  groupExpanded: '<i class="fa-solid fa-caret-down"></i>',
  groupContracted: '<i class="fa-solid fa-caret-right"></i>',
  chart: '<i class="fa-solid fa-chart-column"></i>',
  pivot: '<i class="fa-solid fa-arrows-split-up-and-left"></i>',
  aggFunc: '<i class="fa-solid fa-sigma"></i>',

  // Column Panel
  columnDrag: '<i class="fa-solid fa-grip-lines"></i>',
  columnSelectOpen: '<i class="fa-solid fa-caret-down"></i>',
  columnSelectClosed: '<i class="fa-solid fa-caret-right"></i>',
  sideBarOpen: '<i class="fa-solid fa-chevron-left"></i>',
  sideBarClose: '<i class="fa-solid fa-chevron-right"></i>',
  columnsToolPanel: '<i class="fa-solid fa-table-columns"></i>',
  rowGroup: '<i class="fa-solid fa-layer-group"></i>',
  rowGroupPanel: '<i class="fa-solid fa-layer-group"></i>',
  pivotPanel: '<i class="fa-solid fa-table-list"></i>',
  valuePanel: '<i class="fa-solid fa-bolt"></i>',

  // Filter Panel
  filterOpen: '<i class="fa-solid fa-chevron-down"></i>',
  filterClose: '<i class="fa-solid fa-chevron-right"></i>',
  filterClear: '<i class="fa-solid fa-broom"></i>',
  filterReset: '<i class="fa-solid fa-rotate-left"></i>',
  filterChecked: '<i class="fa-solid fa-check"></i>',
  filterUnchecked: '<i class="fa-regular fa-square"></i>',
  filterList: '<i class="fa-solid fa-list"></i>',
  filterMenu: '<i class="fa-solid fa-filter"></i>',
  filterDelete: '<i class="fa-solid fa-trash"></i>',
  filterEdit: '<i class="fa-solid fa-pen"></i>',
  filterValue: '<i class="fa-solid fa-font"></i>',
  filterOperator: '<i class="fa-solid fa-code-branch"></i>',
  filterExpand: '<i class="fa-solid fa-chevron-down"></i>',
  filterContract: '<i class="fa-solid fa-chevron-right"></i>',

  // Set Filter
  setFilterGroupExpanded: '<i class="fa-solid fa-caret-down"></i>',
  setFilterGroupContracted: '<i class="fa-solid fa-caret-right"></i>',
  setFilterGroupIndeterminate: '<i class="fa-solid fa-minus"></i>',
  setFilterSearch: '<i class="fa-solid fa-magnifying-glass"></i>',
  setFilterSelectAll: '<i class="fa-solid fa-check-double"></i>',
  setFilterSelectNone: '<i class="fa-solid fa-ban"></i>',
  setFilterChecked: '<i class="fa-solid fa-check"></i>',
  setFilterUnchecked: '<i class="fa-regular fa-square"></i>',

  // Conditions
  filterOperatorAnd: '<i class="fa-solid fa-plus"></i>',
  filterOperatorOr: '<i class="fa-solid fa-grip-lines"></i>',
  filterOperatorNot: '<i class="fa-solid fa-not-equal"></i>',
  filterApply: '<i class="fa-solid fa-check"></i>',
  filterCancel: '<i class="fa-solid fa-xmark"></i>',
  filterConditions: '<i class="fa-solid fa-sliders"></i>',
  filterAddCondition: '<i class="fa-solid fa-plus"></i>',
  filterRemoveCondition: '<i class="fa-solid fa-minus"></i>',

  // Charts
  chartLinked: '<i class="fa-solid fa-link"></i>',
  chartUnlinked: '<i class="fa-solid fa-link-slash"></i>',
  chartDownload: '<i class="fa-solid fa-download"></i>',
  chartSettings: '<i class="fa-solid fa-gears"></i>',
  chartData: '<i class="fa-solid fa-database"></i>',
  chartFormat: '<i class="fa-solid fa-paintbrush"></i>',
  chartType: '<i class="fa-solid fa-chart-pie"></i>',
  chartWindow: '<i class="fa-solid fa-window-maximize"></i>',
  chartMenu: '<i class="fa-solid fa-bars-staggered"></i>',

  // Grouping / Tree
  treeOpen: '<i class="fa-solid fa-caret-down"></i>',
  treeClosed: '<i class="fa-solid fa-caret-right"></i>',
  groupRow: '<i class="fa-solid fa-folder"></i>',
  groupLoading: '<i class="fa-solid fa-spinner fa-spin"></i>',
  loading: '<i class="fa-solid fa-spinner fa-spin"></i>',
  loadingSpinner: '<i class="fa-solid fa-circle-notch fa-spin"></i>',
  dragHandle: '<i class="fa-solid fa-grip-vertical"></i>',
  dragHandleVertical: '<i class="fa-solid fa-grip-lines-vertical"></i>',

  // Dragging / Resize
  drag: '<i class="fa-solid fa-grip-lines"></i>',
  smallDrag: '<i class="fa-solid fa-grip-lines-vertical"></i>',
  cursorDrag: '<i class="fa-solid fa-up-down-left-right"></i>',
  resize: '<i class="fa-solid fa-up-down-left-right"></i>',
  resizeLeft: '<i class="fa-solid fa-arrow-left"></i>',
  resizeRight: '<i class="fa-solid fa-arrow-right"></i>',
  resizeTop: '<i class="fa-solid fa-arrow-up"></i>',
  resizeBottom: '<i class="fa-solid fa-arrow-down"></i>',
  resizeHorizontal: '<i class="fa-solid fa-arrows-left-right"></i>',
  resizeVertical: '<i class="fa-solid fa-arrows-up-down"></i>',

  // Clipboard / Actions
  copy: '<i class="fa-solid fa-copy"></i>',
  cut: '<i class="fa-solid fa-scissors"></i>',
  paste: '<i class="fa-solid fa-clipboard"></i>',
  download: '<i class="fa-solid fa-download"></i>',
  save: '<i class="fa-solid fa-floppy-disk"></i>',
  edit: '<i class="fa-solid fa-pen"></i>',
  delete: '<i class="fa-solid fa-trash"></i>',
  tick: '<i class="fa-solid fa-check"></i>',
  cross: '<i class="fa-solid fa-xmark"></i>',
  cancel: '<i class="fa-solid fa-xmark"></i>',
  plus: '<i class="fa-solid fa-plus"></i>',
  minus: '<i class="fa-solid fa-minus"></i>',

  // Misc
  visible: '<i class="fa-solid fa-eye"></i>',
  hidden: '<i class="fa-solid fa-eye-slash"></i>',
  maximize: '<i class="fa-solid fa-maximize"></i>',
  minimize: '<i class="fa-solid fa-minimize"></i>',
  info: '<i class="fa-solid fa-circle-info"></i>',
  warning: '<i class="fa-solid fa-triangle-exclamation"></i>',
};
